[package]
name = "catalogue-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
prost = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.13"
tonic-reflection = "0.13"

[build-dependencies]
tonic-build = "0.13"
prost-build = "0.13"
