FROM rust:1.86-slim AS builder
WORKDIR /backend
COPY . ./
RUN apt update && apt install -y protobuf-compiler
RUN cargo build --package=catalogue --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /backend/target/release/catalogue .
EXPOSE 50051
CMD ["./catalogue", "--port=50051"]
